// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilhrikioshryhiancdjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaHJpa2lvc2hyeWhpYW5jZGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzAyNTUsImV4cCI6MjA3MTcwNjI1NX0.Gm0gDAYl5dk8PfEKH16G_FAUUg_3WkppT_3luzeKK9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});